"""Generate the five static pages; run with Python, no dependencies."""
from pathlib import Path
from html import escape

ROOT = Path(__file__).parent / 'site'
services = [
 ('code','Logiciels sur mesure','Des applications adaptées à vos processus et aux besoins de vos utilisateurs.'),
 ('mobile','Applications mobiles','Des expériences mobiles claires, du prototype à la mise à disposition.'),
 ('web','Plateformes web','Sites, portails et plateformes pour connecter vos services et vos utilisateurs.'),
 ('systems','Solutions IT & intégration','Relier vos outils et vos systèmes pour simplifier la circulation de l’information.'),
 ('cloud','Services numériques','Concevoir et faire évoluer vos services et vos activités en ligne.'),
 ('idea','Conseil & stratégie','Clarifier vos objectifs, vos priorités et les choix techniques de votre projet.'),
 ('support','Maintenance & support','Accompagner le fonctionnement, la correction et l’évolution de vos applications.'),
 ('training','Formation','Aider vos équipes à prendre en main les outils et à développer leurs compétences.')]
icons = {'code':'〈/〉','mobile':'▯','web':'◎','systems':'▤','cloud':'☁','idea':'✧','support':'⚙','training':'◇'}
paths = {'code':'M8 8 4 12l4 4m8-8 4 4-4 4m-3-11-2 14', 'mobile':'M8 2h8a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2m3 17h2', 'web':'M3 12h18M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18m0 0c-5 5-5 13 0 18m0-18c5 5 5 13 0 18', 'systems':'M4 3h16v7H4zm0 11h16v7H4zM7 6h1m-1 11h1', 'cloud':'M6 18a5 5 0 0 1-1-10 7 7 0 0 1 13-1 5.5 5.5 0 0 1 0 11Z', 'idea':'M9 18h6m-6 3h6m-6-6c0-3-4-3-4-7a7 7 0 0 1 14 0c0 4-4 4-4 7Z', 'support':'M12 3v3m0 12v3M3 12h3m12 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10m0 3a2 2 0 1 0 0 4 2 2 0 0 0 0-4', 'training':'M2 8l10-5 10 5-10 5ZM6 10v7c4 3 8 3 12 0v-7m4-2v9'}
icons = {k:f'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="{p}"/></svg>' for k,p in paths.items()}
pages=[('index.html','Accueil'),('solutions.html','Solutions'),('services.html','Services'),('a-propos.html','À propos'),('contact.html','Contact')]

def cards(contact=False):
 return '<div class="service-grid">'+''.join(f'<article class="service-card"><span class="service-icon" aria-hidden="true">{icons[k]}</span><div><h3>{title}</h3><p>{desc}</p><a href="contact.html?service={k}#message">{ "Parlons-en" if contact else "Discuter de ce besoin" } <span aria-hidden="true">→</span></a></div></article>' for k,title,desc in services)+'</div>'

def hero(title,desc,small=False):
 return f'<section class="masthead {"compact" if small else ""}"><div class="wrap mast-grid"><div><p class="eyebrow">GENIE LOGICIEL × INTELLIGENCE ARTIFICIELLE × INNOVATION</p><h1>{title}</h1><p class="intro">{desc}</p><div class="actions"><a class="button" href="contact.html#message">Parlons de votre projet →</a><a class="outline-button" href="services.html#approche">Notre approche</a></div><div class="hero-disciplines"><span>Concevoir</span><span>Développer</span><span>Accompagner</span></div></div><div class="mast-art"><img src="assets/softneur-intelligence.png" alt="" width="1254" height="1254"><span>TECHNOLOGIE<br>AU SERVICE<br>DES USAGES</span></div></div></section>'

def heading(k,t,p=''):
 return f'<div class="section-title"><div><p class="eyebrow">{k}</p><h2>{t}</h2></div><p>{p}</p></div>'

def product():
 return '<section class="wrap product-showcase"><div><p class="eyebrow">UN PRODUIT SOFTNEUR · ÉDUCATION</p><h2>DeepAMC</h2><h3>AMC sur Mobile</h3><p>Une solution pour accompagner les enseignants dans la correction de copies et prolonger leur travail avec Auto Multiple Choice.</p><a class="button" href="https://deepamc.app/">Découvrir DeepAMC ↗</a></div><div class="product-steps"><article><b>01</b><div><h3>Numériser</h3><p>Capturer les feuilles de réponses ou importer des documents déjà scannés.</p></div></article><article><b>02</b><div><h3>Vérifier et corriger</h3><p>Examiner les réponses et les ambiguïtés, puis retrouver les copies annotées.</p></div></article><article><b>03</b><div><h3>Échanger avec AMC</h3><p>Préparer les sujets et transférer les résultats avec DeepAMC Desktop.</p></div></article></div></section>'

def approach():
 steps=[('Comprendre','Échanger sur vos besoins et vos contraintes.'),('Concevoir','Définir les parcours et la solution.'),('Développer','Construire et vérifier les fonctionnalités.'),('Déployer','Préparer la mise à disposition.'),('Accompagner','Suivre les usages et les évolutions.'),('Transmettre','Faciliter la prise en main.')]
 return '<section class="pale" id="approche"><div class="wrap section">'+heading('NOTRE APPROCHE','De l’idée à l’usage.')+'<ol class="process">'+''.join(f'<li><b>{i:02}</b><h3>{t}</h3><p>{d}</p></li>' for i,(t,d) in enumerate(steps,1))+'</ol></div></section>'

home=hero('Logiciels. Applications.<br>Plateformes. <em>Du concret.</em>','Nous concevons des logiciels, des applications mobiles et des plateformes numériques, avec un accompagnement du besoin initial à leur utilisation.')+'<section class="wrap section">'+heading('NOS SERVICES','Des solutions numériques<br>pour vos projets.','Développement, intégration, conseil, maintenance et formation : des compétences complémentaires pour accompagner votre projet.')+cards()+'</section>'+approach()+product()
servicepage=hero('Des services numériques<br>pour les <em>organisations.</em>','Du cadrage au déploiement, SoftNeur vous accompagne dans la conception et l’évolution de vos outils numériques.',True)+'<section class="wrap section">'+heading('NOS SERVICES','Un accompagnement à chaque étape.')+cards()+'</section>'+approach()
solutions=hero('Des idées aux outils.<br><em>Des solutions utiles.</em>','Découvrez les produits SoftNeur et les possibilités de développement pour répondre à vos besoins.',True)+product()+'<section class="pale"><div class="wrap section">'+heading('VOTRE PROJET','Une solution adaptée à votre contexte.','Vous avez besoin d’un outil métier, d’une application ou d’une plateforme ? Décrivons ensemble les usages et les priorités.')+'<a class="button" href="contact.html#message">Présenter mon besoin →</a></div></section>'
about=hero('Une entreprise technologique.<br>Une ambition : <em>être utile.</em>','SoftNeur est spécialisée dans le génie logiciel, les solutions numériques et l’intelligence artificielle.',True)+'<section class="wrap section">'+heading('QUI SOMMES-NOUS ?','Concevoir. Construire.<br>Accompagner.','Nous rapprochons les technologies des besoins concrets des organisations et des personnes. DeepAMC traduit cette démarche dans le domaine de l’éducation.')+'<div class="values"><article><h3>Notre mission</h3><p>Concevoir des outils numériques qui simplifient le travail et ouvrent de nouvelles possibilités.</p></article><article><h3>Notre vision</h3><p>Faire du logiciel et de l’intelligence artificielle des moyens accessibles de répondre à des besoins réels.</p></article><article><h3>Nos principes</h3><p>Écoute, clarté, collaboration et attention portée à la qualité des solutions.</p></article></div></section>'+product()
options=''.join(f'<option value="{k}">{escape(t)}</option>' for k,t,_ in services)
contact=hero('Construisons la suite.<br><em>Ensemble.</em>','Un projet logiciel, une application mobile, une demande de conseil ou de support ? Présentez-nous votre besoin.',True)+f'''<section class="wrap section contact-grid" id="message"><div class="contact-card"><h2>Parlez-nous de votre projet</h2><p>Ce formulaire prépare un e-mail. Vous pourrez le relire et l’envoyer depuis votre messagerie.</p><form id="contact-form"><div class="form-grid"><label>Nom complet *<input name="name" autocomplete="name" required maxlength="120"></label><label>Adresse e-mail *<input name="email" type="email" autocomplete="email" required maxlength="200"></label><label>Organisation<input name="company" autocomplete="organization" maxlength="150"></label><label>Service souhaité *<select name="service" required><option value="">Choisir un service</option>{options}<option value="other">Autre demande</option></select></label><label class="full">Votre message *<textarea name="message" rows="6" required maxlength="3000"></textarea></label></div><button class="button" type="submit">Préparer mon e-mail →</button><p id="form-status" role="status"></p><button type="button" class="copy-button" id="copy-message" hidden>Copier le message</button></form></div><aside class="contact-card"><h2>Nos coordonnées</h2><p>Vous pouvez aussi nous contacter directement.</p><div class="contact-line"><span>E-mail</span><a href="mailto:softneur.wedra@gmail.com">softneur.wedra@gmail.com</a></div><div class="contact-line"><span>Téléphone</span><a href="tel:+22674394847">+226 74 39 48 47</a></div><div class="contact-note"><h3>Pour une demande précise</h3><p>Indiquez le contexte, les utilisateurs concernés, les fonctionnalités souhaitées et vos éventuelles échéances.</p></div></aside></section><section class="wrap section">{heading('COMMENT POUVONS-NOUS VOUS AIDER ?','Choisissez votre besoin.')}{cards(True)}</section><section class="pale"><div class="wrap section"><h2>Questions fréquentes</h2><div class="faq"><details><summary>Que préciser dans ma demande ?</summary><p>Votre objectif, le problème rencontré, les utilisateurs, les contraintes et les documents utiles pour comprendre votre projet.</p></details><details><summary>Le formulaire envoie-t-il directement mon message ?</summary><p>Non. Il ouvre votre messagerie avec un brouillon. L’envoi se fait depuis celle-ci. Si elle ne s’ouvre pas, copiez le message et écrivez directement à softneur.wedra@gmail.com.</p></details><details><summary>Comment découvrir DeepAMC ?</summary><p>Consultez <a href="https://deepamc.app/">le site DeepAMC</a> pour découvrir le produit et ses téléchargements.</p></details><details><summary>Comment aborder la maintenance d’un outil existant ?</summary><p>Décrivez votre application, les technologies utilisées si vous les connaissez et les difficultés ou évolutions souhaitées.</p></details></div></div></section>'''
for (filename,label),content in zip(pages,[home,solutions,servicepage,about,contact]):
 visual = 'softneur-globe.png' if filename in ('contact.html','a-propos.html') else 'softneur-laptop.png'
 content = content.replace('assets/softneur-intelligence.png', 'assets/'+visual)
 if filename == 'index.html':
  strip='<div class="wrap capability-strip">'+''.join(f'<a href="services.html"><span class="service-icon" aria-hidden="true">{icons[k]}</span><span>{t}</span></a>' for k,t in [('code','Logiciels'),('mobile','Applications'),('web','Plateformes'),('systems','Solutions IT'),('cloud','Services numériques')])+'</div>'
  content=content.replace('</section>','</section>'+strip,1)
 nav=''.join(f'<a href="{f}"'+(' aria-current="page"' if f==filename else '')+f'>{l}</a>' for f,l in pages)
 html=f'''<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{label} — SoftNeur</title><meta name="description" content="SoftNeur : logiciels, applications, solutions numériques et intelligence artificielle. {label}."><meta name="theme-color" content="#071b4b"><link rel="stylesheet" href="assets/site.css"><link rel="stylesheet" href="assets/multipage.css"><script src="assets/contact.js" defer></script></head><body><a class="skip" href="#contenu">Aller au contenu</a><header class="header wrap"><a href="index.html" aria-label="SoftNeur, accueil"><img class="logo" src="assets/softneur.svg" width="198" height="64" alt="SoftNeur"></a><nav aria-label="Navigation principale">{nav}</nav><a class="button" href="contact.html#message">Nous contacter →</a></header><main id="contenu">{content}</main><section class="wrap closing"><div><p class="eyebrow">DONNONS FORME À VOTRE PROJET</p><h2>Vos idées. Des solutions concrètes.</h2></div><a class="button" href="contact.html#message">Parlons-en →</a></section><footer class="wrap footer"><a href="index.html"><img class="logo" src="assets/softneur.svg" width="160" height="52" alt="SoftNeur"></a><a href="mailto:softneur.wedra@gmail.com">softneur.wedra@gmail.com</a><a href="tel:+22674394847">+226 74 39 48 47</a><p>© SoftNeur · Where Software Meets Intelligence.</p></footer></body></html>'''
 html=html.replace('</head>','<link rel="stylesheet" href="assets/mockup.css"><link rel="stylesheet" href="assets/brand-motifs.css"></head>')
 html=html.replace('softneur.wedra@gmail.com','contact@softneur.com')
 html=html.replace('</head>','<link rel="stylesheet" href="assets/theme.css"><script src="assets/theme.js"></script></head>')
 html=html.replace('</nav>','</nav><button class="theme-toggle" type="button" aria-label="Activer le mode sombre" aria-pressed="false" hidden>Mode sombre</button>')
 (ROOT/filename).write_text(html,encoding='utf-8')
print('5 pages generated')
